<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV8R8NC5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV8R8NC5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV8R8NC5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV8R8NC5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerV8R8NC5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'V8R8NC5',
    'container.build_id' => 'fa3389a9',
    'container.build_time' => 1588692869,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV8R8NC5');
