<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKFF4OnE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKFF4OnE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKFF4OnE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKFF4OnE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKFF4OnE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KFF4OnE',
    'container.build_id' => '3004bef5',
    'container.build_time' => 1588326375,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKFF4OnE');
