<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2NDVphE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2NDVphE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2NDVphE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2NDVphE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2NDVphE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2NDVphE',
    'container.build_id' => 'd708665e',
    'container.build_time' => 1588255363,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2NDVphE');
